# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eva.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='eva.proto',
  package='eva.msg',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\teva.proto\x12\x07\x65va.msg\"L\n\x04Term\x12\n\n\x02op\x18\x01 \x01(\r\x12\x10\n\x08operands\x18\x02 \x03(\x04\x12&\n\nattributes\x18\x03 \x03(\x0b\x32\x12.eva.msg.Attribute\"E\n\rConstantValue\x12\x0c\n\x04size\x18\x01 \x01(\r\x12\x0e\n\x06values\x18\x02 \x03(\x01\x12\x16\n\x0esparse_indices\x18\x03 \x03(\r\"\x86\x01\n\tAttribute\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\x10\n\x06uint32\x18\x02 \x01(\rH\x00\x12\x0f\n\x05int32\x18\x03 \x01(\x11H\x00\x12\x0e\n\x04type\x18\x04 \x01(\rH\x00\x12\x30\n\x0e\x63onstant_value\x18\x05 \x01(\x0b\x32\x16.eva.msg.ConstantValueH\x00\x42\x07\n\x05value\"&\n\x08TermName\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x0c\n\x04name\x18\x02 \x01(\t\"\xa2\x01\n\x07Program\x12\x12\n\nir_version\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08vec_size\x18\x03 \x01(\r\x12\x1c\n\x05terms\x18\x04 \x03(\x0b\x32\r.eva.msg.Term\x12!\n\x06inputs\x18\x05 \x03(\x0b\x32\x11.eva.msg.TermName\x12\"\n\x07outputs\x18\x06 \x03(\x0b\x32\x11.eva.msg.TermNameb\x06proto3'
)




_TERM = _descriptor.Descriptor(
  name='Term',
  full_name='eva.msg.Term',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='op', full_name='eva.msg.Term.op', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='operands', full_name='eva.msg.Term.operands', index=1,
      number=2, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='attributes', full_name='eva.msg.Term.attributes', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=98,
)


_CONSTANTVALUE = _descriptor.Descriptor(
  name='ConstantValue',
  full_name='eva.msg.ConstantValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='size', full_name='eva.msg.ConstantValue.size', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='values', full_name='eva.msg.ConstantValue.values', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sparse_indices', full_name='eva.msg.ConstantValue.sparse_indices', index=2,
      number=3, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=169,
)


_ATTRIBUTE = _descriptor.Descriptor(
  name='Attribute',
  full_name='eva.msg.Attribute',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='eva.msg.Attribute.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uint32', full_name='eva.msg.Attribute.uint32', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='int32', full_name='eva.msg.Attribute.int32', index=2,
      number=3, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='eva.msg.Attribute.type', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='constant_value', full_name='eva.msg.Attribute.constant_value', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='value', full_name='eva.msg.Attribute.value',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=172,
  serialized_end=306,
)


_TERMNAME = _descriptor.Descriptor(
  name='TermName',
  full_name='eva.msg.TermName',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='term', full_name='eva.msg.TermName.term', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='eva.msg.TermName.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=308,
  serialized_end=346,
)


_PROGRAM = _descriptor.Descriptor(
  name='Program',
  full_name='eva.msg.Program',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ir_version', full_name='eva.msg.Program.ir_version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='eva.msg.Program.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vec_size', full_name='eva.msg.Program.vec_size', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='terms', full_name='eva.msg.Program.terms', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='inputs', full_name='eva.msg.Program.inputs', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='outputs', full_name='eva.msg.Program.outputs', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=349,
  serialized_end=511,
)

_TERM.fields_by_name['attributes'].message_type = _ATTRIBUTE
_ATTRIBUTE.fields_by_name['constant_value'].message_type = _CONSTANTVALUE
_ATTRIBUTE.oneofs_by_name['value'].fields.append(
  _ATTRIBUTE.fields_by_name['uint32'])
_ATTRIBUTE.fields_by_name['uint32'].containing_oneof = _ATTRIBUTE.oneofs_by_name['value']
_ATTRIBUTE.oneofs_by_name['value'].fields.append(
  _ATTRIBUTE.fields_by_name['int32'])
_ATTRIBUTE.fields_by_name['int32'].containing_oneof = _ATTRIBUTE.oneofs_by_name['value']
_ATTRIBUTE.oneofs_by_name['value'].fields.append(
  _ATTRIBUTE.fields_by_name['type'])
_ATTRIBUTE.fields_by_name['type'].containing_oneof = _ATTRIBUTE.oneofs_by_name['value']
_ATTRIBUTE.oneofs_by_name['value'].fields.append(
  _ATTRIBUTE.fields_by_name['constant_value'])
_ATTRIBUTE.fields_by_name['constant_value'].containing_oneof = _ATTRIBUTE.oneofs_by_name['value']
_PROGRAM.fields_by_name['terms'].message_type = _TERM
_PROGRAM.fields_by_name['inputs'].message_type = _TERMNAME
_PROGRAM.fields_by_name['outputs'].message_type = _TERMNAME
DESCRIPTOR.message_types_by_name['Term'] = _TERM
DESCRIPTOR.message_types_by_name['ConstantValue'] = _CONSTANTVALUE
DESCRIPTOR.message_types_by_name['Attribute'] = _ATTRIBUTE
DESCRIPTOR.message_types_by_name['TermName'] = _TERMNAME
DESCRIPTOR.message_types_by_name['Program'] = _PROGRAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Term = _reflection.GeneratedProtocolMessageType('Term', (_message.Message,), {
  'DESCRIPTOR' : _TERM,
  '__module__' : 'eva_pb2'
  # @@protoc_insertion_point(class_scope:eva.msg.Term)
  })
_sym_db.RegisterMessage(Term)

ConstantValue = _reflection.GeneratedProtocolMessageType('ConstantValue', (_message.Message,), {
  'DESCRIPTOR' : _CONSTANTVALUE,
  '__module__' : 'eva_pb2'
  # @@protoc_insertion_point(class_scope:eva.msg.ConstantValue)
  })
_sym_db.RegisterMessage(ConstantValue)

Attribute = _reflection.GeneratedProtocolMessageType('Attribute', (_message.Message,), {
  'DESCRIPTOR' : _ATTRIBUTE,
  '__module__' : 'eva_pb2'
  # @@protoc_insertion_point(class_scope:eva.msg.Attribute)
  })
_sym_db.RegisterMessage(Attribute)

TermName = _reflection.GeneratedProtocolMessageType('TermName', (_message.Message,), {
  'DESCRIPTOR' : _TERMNAME,
  '__module__' : 'eva_pb2'
  # @@protoc_insertion_point(class_scope:eva.msg.TermName)
  })
_sym_db.RegisterMessage(TermName)

Program = _reflection.GeneratedProtocolMessageType('Program', (_message.Message,), {
  'DESCRIPTOR' : _PROGRAM,
  '__module__' : 'eva_pb2'
  # @@protoc_insertion_point(class_scope:eva.msg.Program)
  })
_sym_db.RegisterMessage(Program)


# @@protoc_insertion_point(module_scope)
